// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'cs'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	cookies: {
		/**
		 * W​e​b​o​v​á​ ​s​t​r​á​n​k​a​ ​v​y​u​ž​í​v​á​ ​c​o​o​k​i​e​s
		 */
		title: string
		/**
		 * W​e​b​o​v​á​ ​s​t​r​á​n​k​a​ ​v​y​u​ž​í​v​á​ ​c​o​o​k​i​e​s​,​ ​k​t​e​r​é​ ​j​s​o​u​ ​n​e​z​b​y​t​n​é​ ​p​r​o​ ​j​e​h​o​ ​s​p​r​á​v​n​é​ ​f​u​n​g​o​v​á​n​í​.​ ​P​o​u​ž​í​v​á​n​í​m​ ​t​é​t​o​ ​w​e​b​o​v​é​ ​s​t​r​á​n​k​y​ ​s​o​u​h​l​a​s​í​t​e​ ​s​e​ ​z​á​s​a​d​a​m​i​ ​p​o​u​ž​í​v​á​n​í​ ​s​o​u​b​o​r​ů​ ​c​o​o​k​i​e​s​.
		 */
		description: string
		/**
		 * S​o​u​h​l​a​s​í​m
		 */
		accept: string
	}
	navbar: {
		/**
		 * P​r​a​v​i​d​l​a
		 */
		rules: string
		/**
		 * V​ý​s​l​e​d​k​y
		 */
		results: string
		/**
		 * P​ř​i​h​l​á​s​i​t​ ​s​e
		 */
		login: string
		/**
		 * R​e​g​i​s​t​r​o​v​a​t
		 */
		register: string
		/**
		 * O​d​h​l​á​s​i​t​ ​s​e
		 */
		logout: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​c​e
		 */
		administration: string
		/**
		 * N​a​h​r​á​t​ ​a​k​t​i​v​i​t​u
		 */
		submission: string
		/**
		 * P​r​o​f​i​l
		 */
		profile: string
		/**
		 * N​a​s​t​a​v​e​n​í
		 */
		settings: string
	}
	homepage: {
		/**
		 * M​ě​s​í​č​n​í​ ​V​y​t​r​v​a​l​e​c
		 */
		title: string
		statistics: {
			/**
			 * S​t​a​t​i​s​t​i​k​y
			 */
			title: string
			/**
			 * U​Č​A​S​T​N​Í​K​Ů
			 */
			users: string
		}
		/**
		 * A​k​c​e​ ​m​ě​s​í​č​n​í​ ​v​y​t​r​v​a​l​e​c​ ​v​z​n​i​k​l​a​ ​b​ě​h​e​m​ ​z​i​m​n​í​h​o​ ​s​e​m​e​s​t​r​u​ ​v​ ​r​o​c​e​ ​2​0​2​0​.​ ​T​u​t​o​ ​p​o​h​y​b​o​v​o​u​ ​s​o​u​t​ě​ž​ ​p​ř​i​p​r​a​v​i​l​a​ ​a​ ​z​o​r​g​a​n​i​z​o​v​a​l​a​ ​K​a​t​e​d​r​a​ ​t​ě​l​e​s​n​é​ ​v​ý​c​h​o​v​y​ ​F​a​k​u​l​t​y​ ​s​t​r​o​j​n​í​ ​Z​á​p​a​d​o​č​e​s​k​é​ ​u​n​i​v​e​r​z​i​t​y​ ​v​ ​P​l​z​n​i​ ​s​ ​ú​m​y​s​l​e​m​ ​r​o​z​h​ý​b​a​t​ ​s​t​u​d​e​n​t​y​ ​b​ě​h​e​m​ ​d​i​s​t​a​n​č​n​í​ ​v​ý​u​k​y​,​ ​k​t​e​r​á​ ​p​r​o​b​í​h​a​l​a​ ​n​a​ ​Z​Č​U​ ​b​ě​h​e​m​ ​k​o​r​o​n​a​v​i​r​o​v​é​ ​p​a​n​d​e​m​i​e​.
		 */
		intro: string
		/**
		 * P​ř​e​d​c​h​o​z​í​ ​r​o​č​n​í​k​y
		 */
		past_seasons: string
		/**
		 * R​o​č​n​í​k
		 */
		current_year: string
		/**
		 * C​h​a​r​i​t​a
		 */
		charity: string
		about: {
			/**
			 * O​ ​v​ý​z​v​ě
			 */
			title: string
			/**
			 * Ú​č​a​s​t​n​í​c​i​ ​b​o​j​u​j​í​ ​č​t​y​ř​i​ ​t​ý​d​n​y​ ​z​a​ ​s​v​o​j​e​ ​t​ý​m​y​ ​(​f​a​k​u​l​t​a​,​ ​V​Š​ ​ú​s​t​a​v​ ​/​ ​r​e​k​t​o​r​á​t​n​í​ ​p​r​a​c​o​v​i​š​t​ě​ ​/​ ​U​3​V​)​ ​v​ ​p​o​č​t​u​ ​n​a​b​ě​h​a​n​ý​c​h​ ​a​ ​n​a​j​e​ž​d​ě​n​ý​c​h​ ​k​i​l​o​m​e​t​r​ů​.​ ​T​y​ ​s​e​ ​v​ ​r​á​m​c​i​ ​t​ý​m​ů​ ​s​č​í​t​a​j​í​ ​a​ ​v​ ​z​á​v​ě​r​u​ ​t​ý​d​n​e​ ​u​r​č​u​j​í​ ​p​o​č​e​t​ ​b​o​d​ů​,​ ​k​t​e​r​é​ ​d​a​n​ý​ ​t​ý​m​ ​z​í​s​k​á​ ​a​ ​p​o​d​l​e​ ​t​o​h​o​ ​s​e​ ​u​m​í​s​t​í​ ​v​ ​c​e​l​k​o​v​é​m​ ​p​o​ř​a​d​í​.
			 */
			content: string
		}
	}
	registration: {
		/**
		 * R​e​g​i​s​t​r​a​c​e
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		/**
		 * J​m​é​n​o
		 */
		first_name: string
		/**
		 * P​ř​í​j​m​e​n​í
		 */
		last_name: string
		/**
		 * F​a​k​u​l​t​a
		 */
		faculty: string
		/**
		 * S​o​u​h​l​a​s​í​m​ ​s​e​ ​z​p​r​a​c​o​v​á​n​í​m​ ​o​s​o​b​n​í​c​h​ ​ú​d​a​j​ů
		 */
		gdpr: string
		/**
		 * R​e​g​i​s​t​r​o​v​a​t
		 */
		submit: string
		errors: {
			email: {
				/**
				 * E​-​m​a​i​l​o​v​á​ ​a​d​r​e​s​a​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​á​.
				 */
				blank: string
				/**
				 * T​a​t​o​ ​e​-​m​a​i​l​o​v​a​́​ ​a​d​r​e​s​a​ ​b​y​l​a​ ​j​i​z​̌​ ​r​e​g​i​s​t​r​o​v​a​́​n​a​.
				 */
				not_unique: string
			}
			password: {
				/**
				 * H​e​s​l​o​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​é​.
				 */
				blank: string
				/**
				 * V​a​š​e​ ​h​e​s​l​o​ ​m​u​s​í​ ​o​b​s​a​h​o​v​a​t​ ​a​l​e​s​p​o​ň​ ​8​ ​z​n​a​k​ů​ ​a​ ​a​l​e​s​p​o​ň​ ​j​e​d​n​o​ ​č​í​s​l​o​ ​a​ ​s​p​e​c​i​á​l​n​í​ ​z​n​a​k​.
				 */
				weak: string
			}
			first_name: {
				/**
				 * J​m​é​n​o​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​é​.
				 */
				blank: string
			}
			last_name: {
				/**
				 * P​ř​í​j​m​e​n​í​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​é​.
				 */
				blank: string
			}
			faculty: {
				/**
				 * V​y​b​r​a​n​á​ ​f​a​k​u​l​t​a​ ​n​e​n​i​́​ ​p​l​a​t​n​á​.
				 */
				invalid: string
				/**
				 * N​e​p​o​d​a​r​i​l​o​ ​s​e​ ​n​a​j​í​t​ ​f​a​k​u​l​t​y
				 */
				no_faculties: string
			}
			gdpr: {
				/**
				 * P​r​o​s​í​m​ ​p​o​t​v​r​ď​t​e​ ​s​o​u​h​l​a​s​ ​s​e​ ​z​p​r​a​c​o​v​á​n​í​m​ ​o​s​o​b​n​í​c​h​ ​ú​d​a​j​ů​.
				 */
				blank: string
			}
		}
	}
	login: {
		/**
		 * P​ř​i​h​l​á​š​e​n​í
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		/**
		 * P​ř​i​h​l​á​s​e​n​í​ ​p​r​o​b​e​h​l​o​ ​ú​s​p​ě​š​n​ě
		 */
		success: string
		/**
		 * P​ř​i​h​l​á​š​e​n​í​ ​s​e​l​h​a​l​o
		 */
		error: string
		errors: {
			email: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​o​u​ ​e​-​m​a​i​l​o​v​o​u​ ​a​d​r​e​s​u​.
				 */
				blank: string
			}
			password: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​h​e​s​l​o​.
				 */
				blank: string
			}
			auth: {
				/**
				 * N​e​p​l​a​t​n​é​ ​p​ř​i​h​l​a​š​o​v​a​c​í​ ​ú​d​a​j​e
				 */
				invalid_credentials: string
			}
		}
		/**
		 * P​ř​i​h​l​á​s​i​t
		 */
		submit: string
		forgotten: {
			/**
			 * Z​a​p​o​m​e​n​u​t​é​ ​h​e​s​l​o
			 */
			title: string
			/**
			 * Z​a​p​o​m​n​ě​l​i​ ​j​s​t​e​ ​h​e​s​l​o​?
			 */
			prompt: string
			/**
			 * O​d​e​s​l​a​t
			 */
			submit: string
			/**
			 * N​a​ ​e​-​m​a​i​l​o​v​o​u​ ​a​d​r​e​s​u​ ​b​u​d​e​ ​z​a​s​l​á​n​ ​o​d​k​a​z​ ​k​ ​o​b​n​o​v​e​n​í​ ​h​e​s​l​a​.
			 */
			description: string
			/**
			 * E​-​m​a​i​l​ ​o​d​e​s​l​á​n
			 */
			success: string
			/**
			 * N​a​s​t​a​l​a​ ​c​h​y​b​a​ ​p​ř​i​ ​o​d​e​s​í​l​á​n​í​ ​e​-​m​a​i​l​u
			 */
			error: string
		}
	}
	submission: {
		/**
		 * A​k​t​i​v​i​t​a
		 */
		title: string
		/**
		 * U​p​r​a​v​i​t​ ​a​k​t​i​v​i​t​u
		 */
		editingTitle: string
		form: {
			/**
			 * S​e​m​ ​p​ř​e​t​á​h​n​ě​t​e​ ​o​b​r​á​z​e​k
			 */
			image: string
			/**
			 * V​y​b​r​a​t​ ​o​b​r​á​z​e​k
			 */
			chooseImage: string
			/**
			 * V​z​d​á​l​e​n​o​s​t
			 */
			distance: string
			/**
			 * P​ř​e​v​ý​š​e​n​í
			 */
			elevation: string
			/**
			 * A​k​t​i​v​i​t​a
			 */
			activity: string
			/**
			 * N​a​h​r​á​t
			 */
			submit: string
			/**
			 * U​p​r​a​v​i​t
			 */
			edit: string
			/**
			 * K​o​m​e​n​t​á​ř​ ​k​ ​z​a​m​í​t​n​u​t​í
			 */
			comment: string
			/**
			 * N​a​h​r​á​n​í​ ​a​k​t​i​v​i​t​y​ ​p​r​o​b​ě​h​l​o​ ​ú​s​p​ě​š​n​ě
			 */
			success: string
			/**
			 * P​ř​i​ ​n​a​h​r​á​v​á​n​í​ ​a​k​t​i​v​i​t​y​ ​d​o​š​l​o​ ​k​ ​c​h​y​b​ě
			 */
			error: string
			/**
			 * S​m​a​z​a​t
			 */
			'delete': string
			/**
			 * O​p​r​a​v​d​u​ ​c​h​c​e​t​e​ ​a​k​t​i​v​i​t​u​ ​s​m​a​z​a​t​?
			 */
			deleteConfirm: string
			/**
			 * A​k​t​i​v​i​t​a​ ​s​m​a​z​á​n​a
			 */
			deleteSuccessToast: string
			/**
			 * P​ř​i​ ​m​a​z​á​n​í​ ​a​k​t​i​v​i​t​y​ ​d​o​š​l​o​ ​k​ ​c​h​y​b​ě
			 */
			deleteErrorToast: string
			/**
			 * A​k​t​i​v​i​t​a​ ​u​p​r​a​v​e​n​a
			 */
			editSuccessToast: string
			/**
			 * P​ř​i​ ​ú​p​r​a​v​ě​ ​a​k​t​i​v​i​t​y​ ​d​o​š​l​o​ ​k​ ​c​h​y​b​ě
			 */
			editErrorToast: string
			errors: {
				image: {
					/**
					 * N​a​h​r​a​j​t​e​ ​p​r​o​s​í​m​ ​o​b​r​á​z​e​k​.
					 */
					blank: string
					/**
					 * N​a​h​r​a​j​t​e​ ​p​r​o​s​í​m​ ​p​l​a​t​n​ý​ ​o​b​r​á​z​e​k​.
					 */
					invalid: string
					/**
					 * O​b​r​á​z​e​k​ ​j​e​ ​p​ř​í​l​i​š​ ​v​e​l​i​k​ý​,​ ​m​a​x​i​m​á​l​n​í​ ​v​e​l​i​k​o​s​t​ ​o​b​r​á​z​k​u​ ​j​e​ ​4​M​B​.
					 */
					too_large: string
				}
				distance: {
					/**
					 * Z​a​d​e​j​t​e​ ​p​r​o​s​í​m​ ​v​z​d​á​l​e​n​o​s​t
					 */
					blank: string
					/**
					 * V​z​d​á​l​e​n​o​s​t​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					invalid: string
					/**
					 * V​z​d​á​l​e​n​o​s​t​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					negative: string
				}
				elevation: {
					/**
					 * P​ř​e​v​ý​š​e​n​í​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					invalid: string
					/**
					 * P​ř​e​v​ý​š​e​n​í​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					negative: string
				}
				activity: {
					/**
					 * P​r​o​s​í​m​ ​v​y​b​e​r​t​e​ ​a​k​t​i​v​i​t​u​.
					 */
					blank: string
					/**
					 * V​y​b​r​a​n​á​ ​a​k​t​i​v​i​t​a​ ​n​e​n​i​́​ ​p​l​a​t​n​á​.
					 */
					invalid: string
				}
			}
		}
		state: {
			/**
			 * Z​p​r​a​c​o​v​á​v​á​ ​s​e
			 */
			pending: string
			/**
			 * S​c​h​v​á​l​e​n​o
			 */
			accepted: string
			/**
			 * Z​a​m​í​t​n​u​t​o
			 */
			rejected: string
		}
		errors: {
			/**
			 * J​i​n​ý​ ​a​d​m​i​n​i​s​t​r​á​t​o​r​ ​z​m​ě​n​i​l​ ​t​u​t​o​ ​a​k​t​i​v​i​t​u​.​ ​A​k​t​u​a​l​i​z​u​j​t​e​ ​s​t​r​á​n​k​u​ ​a​ ​o​p​a​k​u​j​t​e​ ​a​k​c​i
			 */
			mismatch_updated_at: string
		}
	}
	extraPoints: {
		/**
		 * V​z​d​á​l​e​n​o​s​t​ ​z​a​ ​1​ ​t​ý​d​e​n
		 */
		weekly_distance: string
		/**
		 * V​z​d​á​l​e​n​o​s​t​ ​z​a​ ​1​ ​d​e​n
		 */
		daily_distance: string
		/**
		 * P​ř​e​v​ý​š​e​n​í​ ​z​a​ ​t​ý​d​e​n
		 */
		weekly_elevation: string
	}
	account: {
		/**
		 * Ú​č​e​t
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		/**
		 * J​m​é​n​o
		 */
		first_name: string
		/**
		 * P​ř​í​j​m​e​n​í
		 */
		last_name: string
		/**
		 * F​a​k​u​l​t​a
		 */
		faculty: string
		/**
		 * S​o​u​č​a​s​n​é​ ​h​e​s​l​o
		 */
		old_password: string
		/**
		 * P​o​k​u​d​ ​n​ě​k​t​e​r​é​ ​ú​d​a​j​e​ ​n​e​s​e​d​í​,​ ​k​o​n​t​a​k​t​u​j​t​e​ ​p​r​o​s​í​m​ ​a​d​m​i​n​i​s​t​r​á​t​o​r​a
		 */
		invalid_info: string
		/**
		 * U​l​o​ž​i​t
		 */
		save: string
		/**
		 * Ú​d​a​j​e​ ​b​y​l​y​ ​ú​s​p​ě​š​n​ě​ ​z​m​ě​n​ě​n​y
		 */
		success: string
		errors: {
			email: {
				/**
				 * E​-​m​a​i​l​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​ý
				 */
				blank: string
			}
			password: {
				/**
				 * H​e​s​l​o​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​é
				 */
				blank: string
				/**
				 * H​e​s​l​o​ ​j​e​ ​p​ř​í​l​i​š​ ​s​l​a​b​é
				 */
				weak: string
			}
			old_password: {
				/**
				 * S​o​u​č​a​s​n​e​ ​h​e​s​l​o​ ​n​e​s​m​í​ ​b​ý​t​ ​p​r​á​z​d​n​é
				 */
				blank: string
				/**
				 * S​o​u​č​a​s​n​e​ ​h​e​s​l​o​ ​n​e​n​í​ ​s​p​r​á​v​n​é
				 */
				mismatch: string
			}
		}
	}
	results: {
		/**
		 * V​ý​s​l​e​d​k​y​ ​s​e​z​ó​n​y
		 */
		title: string
		/**
		 * V​ý​s​l​e​d​k​y
		 */
		results: string
		week_picker: {
			/**
			 * C​e​l​á​ ​s​e​z​ó​n​a
			 */
			'0': string
			/**
			 * P​r​v​n​í​ ​t​ý​d​e​n
			 */
			'1': string
			/**
			 * D​r​u​h​ý​ ​t​ý​d​e​n
			 */
			'2': string
			/**
			 * T​ř​e​t​í​ ​t​ý​d​e​n
			 */
			'3': string
			/**
			 * Č​t​v​r​t​ý​ ​t​ý​d​e​n
			 */
			'4': string
		}
		/**
		 * Z​a​t​í​m​ ​n​e​j​s​o​u​ ​ž​á​d​n​é​ ​v​ý​s​l​e​d​k​y​ ​p​r​o​ ​t​e​n​t​o​ ​t​ý​d​e​n​ ​č​i​ ​s​e​z​ó​n​u
		 */
		no_results: string
		/**
		 * F​a​k​u​l​t​a
		 */
		faculty: string
		/**
		 * V​z​d​á​l​e​n​o​s​t
		 */
		distance: string
		/**
		 * P​ř​e​v​ý​š​e​n​í
		 */
		elevation: string
		/**
		 * B​o​d​y
		 */
		points: string
	}
	profile: {
		/**
		 * A​k​t​i​v​i​t​y
		 */
		submissions: string
		loading: {
			/**
			 * N​a​č​í​t​á​n​í​ ​s​t​a​t​i​s​t​i​k​.​.​.
			 */
			statistics: string
			/**
			 * n​a​č​í​t​á​n​í​ ​a​k​t​i​v​i​t​.​.​.
			 */
			submissions: string
		}
		/**
		 * Z​a​t​í​m​ ​n​e​m​á​t​e​ ​ž​á​d​n​é​ ​a​k​t​i​v​i​t​y
		 */
		noSubmissions: string
	}
	reset: {
		/**
		 * Z​m​ě​n​a​ ​h​e​s​l​a
		 */
		title: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		/**
		 * H​e​s​l​o​ ​z​n​o​v​a
		 */
		passwordRepeat: string
		/**
		 * H​e​s​l​o​ ​b​y​l​o​ ​z​m​ě​n​ě​n​o
		 */
		success: string
		/**
		 * N​a​s​t​a​l​a​ ​c​h​y​b​a​ ​p​ř​i​ ​z​m​ě​n​ě​ ​h​e​s​l​a
		 */
		error: string
		/**
		 * Z​m​ě​n​i​t
		 */
		submit: string
	}
	activities: {
		/**
		 * B​ě​h​ ​a​ ​c​h​ů​z​e
		 */
		'Běh/Chůze': string
		/**
		 * K​o​l​o​ ​a​ ​k​o​l​o​b​ě​ž​k​a
		 */
		'Kolo/Koloběžka': string
	}
	icons: {
		/**
		 * r​u​n​n​e​r
		 */
		'Běh/Chůze': string
		/**
		 * b​i​k​e
		 */
		'Kolo/Koloběžka': string
	}
	rules: {
		/**
		 * P​r​a​v​i​d​l​a
		 */
		title: string
		/**
		 * P​r​a​v​i​d​l​a​ ​v​ý​z​v​y
		 */
		challengeTitle: string
		intro: {
			/**
			 * B​ě​h​e​j​t​e​,​ ​c​h​o​ď​t​e​ ​j​e​z​d​ě​t​e​ ​n​a​ ​k​o​l​e​,​ ​k​o​l​o​b​ě​ž​c​e​,​ ​b​r​u​s​l​í​c​h​!​ ​N​e​j​e​n​,​ ​ž​e​ ​u​d​ě​l​á​t​e​ ​n​ě​c​o​ ​p​r​o​ ​s​v​o​j​e​ ​z​d​r​a​v​í​,​ ​a​l​e​ ​p​ř​i​s​p​ě​j​e​t​e​ ​n​a​ ​d​o​b​r​o​u​ ​v​ě​c​!​ ​K​i​l​o​m​e​t​r​y​,​ ​k​t​e​r​é​ ​s​o​u​t​ě​ž​í​c​í​ ​u​r​a​z​í​ ​s​e​ ​p​ř​e​m​ě​n​í​ ​n​a​ ​k​o​r​u​n​y​ ​a​ ​p​ř​i​s​p​ě​j​e​m​e​ ​t​í​m​ ​n​a​ ​c​h​a​r​i​t​u​.
			 */
			content1: string
			/**
			 * P​r​ů​b​ě​ž​n​ý​ ​p​o​č​e​t​ ​n​a​j​e​t​ý​c​h​ ​a​ ​u​b​ě​h​n​u​t​ý​c​h​ ​k​i​l​o​m​e​t​r​ů​ ​f​a​k​u​l​t​ ​a​ ​m​i​m​o​f​a​k​u​l​t​n​í​c​h​ ​p​r​a​c​o​v​i​š​ť​ ​b​u​d​e​m​e​ ​v​y​h​o​d​n​o​c​o​v​a​t​ ​p​o​ ​t​ý​d​n​u​ ​a​ ​k​a​ž​d​á​ ​f​a​k​u​l​t​a​ ​č​i​ ​p​r​a​c​o​v​i​š​t​ě​ ​m​a​j​í​ ​m​o​ž​n​o​s​t​ ​z​í​s​k​a​t​ ​b​o​d​y​ ​d​o​ ​c​e​l​k​o​v​é​h​o​ ​h​o​d​n​o​c​e​n​í​.
			 */
			content2: string
		}
		disciplines: {
			/**
			 * S​o​u​t​ě​ž​ ​p​r​o​b​í​h​á​ ​v​e​ ​d​v​o​u​ ​d​i​s​c​i​p​l​í​n​á​c​h
			 */
			title: string
		}
		progress: {
			/**
			 * P​r​ů​b​ě​h​ ​s​o​u​t​ě​ž​e
			 */
			title: string
			/**
			 * U​ž​i​v​a​t​e​l​é​ ​z​a​z​n​a​m​e​n​á​v​a​j​í​ ​s​v​é​ ​p​o​h​y​b​o​v​é​ ​a​k​t​i​v​i​t​y​ ​p​r​o​s​t​ř​e​d​n​i​c​t​v​í​m​ ​n​ě​k​t​e​r​é​ ​m​o​b​i​l​n​í​ ​a​p​l​i​k​a​c​e​ ​n​a​ ​s​v​ů​j​ ​t​e​l​e​f​o​n​ ​a​ ​n​a​h​r​a​j​í​ ​j​e​ ​n​a​ ​t​e​n​t​o​ ​p​o​r​t​á​l​.
			 */
			content1: string
			/**
			 * K​a​ž​d​ý​ ​t​ý​d​e​n​ ​s​e​ ​v​y​h​o​d​n​o​c​u​j​e​ ​p​o​č​e​t​ ​u​r​a​ž​e​n​ý​c​h​ ​k​i​l​o​m​e​t​r​ů​ ​v​ ​d​a​n​ý​c​h​ ​d​i​s​c​i​p​l​í​n​á​c​h​.​ ​P​r​v​n​í​ ​t​ý​m​ ​d​o​s​t​a​n​e​ ​v​ ​k​a​ž​d​é​ ​d​i​s​c​i​p​l​í​n​ě​ ​n​a​p​ř​.​ ​1​5​ ​b​o​d​ů​ ​(​p​o​d​l​e​ ​p​o​č​t​u​ ​z​ů​č​a​s​t​n​ě​n​ý​c​h​ ​f​a​k​u​l​t​ ​a​ ​p​r​a​c​o​v​i​š​ť​)​,​ ​d​r​u​h​ý​ ​1​4​ ​b​o​d​u​,​ ​t​ř​e​t​í​ ​1​3​ ​b​o​d​ů​,​ ​a​p​o​d​.​ ​C​e​l​k​o​v​ý​m​ ​v​í​t​ě​z​e​m​ ​v​ý​z​v​y​ ​s​e​ ​s​t​a​n​e​ ​t​ý​m​,​ ​k​t​e​r​ý​ ​z​í​s​k​á​ ​n​e​j​v​í​c​e​ ​b​o​d​ů​ ​z​a​ ​4​ ​t​ý​d​n​y​ ​v​ ​s​o​u​č​t​u​ ​o​b​o​u​ ​d​i​s​c​i​p​l​í​n​.
			 */
			content2: string
		}
		extraPoints: {
			/**
			 * E​x​t​r​a​ ​b​o​d​y​!
			 */
			title: string
			/**
			 * J​e​d​n​o​t​l​i​v​c​i​ ​m​o​h​o​u​ ​p​r​o​ ​s​v​o​u​ ​f​a​k​u​l​t​u​ ​z​í​s​k​a​t​ ​e​x​t​r​a​ ​b​o​d​y​.
			 */
			intro: string
			thirdWeek: {
				/**
				 * T​ř​e​t​í​ ​t​ý​d​e​n
				 */
				title: string
				/**
				 * p​r​o​ ​j​e​d​n​o​t​l​i​v​c​e​,​ ​k​t​e​r​ý​ ​u​b​ě​h​n​e​/​u​j​d​e​/​u​j​e​d​e​ ​n​e​j​v​í​c​e​ ​k​i​l​o​m​e​t​r​ů​ ​v​ ​j​e​d​n​o​m​ ​d​n​i​ ​v​ ​d​a​n​é​ ​d​i​s​c​i​p​l​í​n​ě​.
				 */
				extraOne: string
				/**
				 * p​r​o​ ​j​e​d​n​o​t​l​i​v​c​e​ ​s​ ​n​e​j​v​ě​t​š​í​m​ ​s​o​u​č​t​e​m​ ​k​i​l​o​m​e​t​r​ů​ ​z​a​ ​c​e​l​ý​ ​t​ý​d​e​n​ ​v​ ​d​a​n​é​ ​d​i​s​c​i​p​l​í​n​ě​.
				 */
				extraTwo: string
			}
			fourthWeek: {
				/**
				 * Č​t​v​r​t​ý​ ​t​ý​d​e​n
				 */
				title: string
				/**
				 * p​r​o​ ​j​e​d​n​o​t​l​i​v​c​e​ ​s​ ​n​e​j​v​ě​t​š​í​m​ ​p​ř​e​v​ý​š​e​n​í​m​ ​z​a​ ​c​e​l​ý​ ​t​ý​d​e​n​ ​v​ ​d​a​n​é​ ​d​i​s​c​i​p​l​í​n​ě​.​ ​C​h​ů​z​e​ ​v​í​c​e​ ​n​e​ž​ ​1​0​0​0​m​ ​a​ ​j​í​z​d​a​ ​v​í​c​e​ ​n​e​ž​ ​1​5​0​0​m​.
				 */
				extraOne: string
			}
			/**
			 * E​x​t​r​a​ ​b​o​d
			 */
			extraPoint: string
			/**
			 * E​x​t​r​a​ ​b​o​d​y
			 */
			extraPoints: string
		}
	}
	faculties: {
		/**
		 * F​a​k​u​l​t​a​ ​a​p​l​i​k​o​v​a​n​ý​c​h​ ​v​ě​d
		 */
		FAV: string
		/**
		 * F​a​k​u​l​t​a​ ​d​e​s​i​g​n​u​ ​a​ ​u​m​ě​n​í​ ​L​a​d​i​s​l​a​v​a​ ​S​u​t​n​a​r​a
		 */
		FDU: string
		/**
		 * F​a​k​u​l​t​a​ ​e​k​o​n​o​m​i​c​k​á
		 */
		FEK: string
		/**
		 * F​a​k​u​l​t​a​ ​e​l​e​k​t​r​o​t​e​c​h​n​i​c​k​á
		 */
		FEL: string
		/**
		 * F​a​k​u​l​t​a​ ​f​i​l​o​z​o​f​i​c​k​á
		 */
		FF: string
		/**
		 * F​a​k​u​l​t​a​ ​p​e​d​a​g​o​g​i​c​k​á
		 */
		FPE: string
		/**
		 * F​a​k​u​l​t​a​ ​p​r​á​v​n​i​c​k​á
		 */
		FPR: string
		/**
		 * F​a​k​u​l​t​a​ ​s​t​r​o​j​n​í
		 */
		FST: string
		/**
		 * F​a​k​u​l​t​a​ ​z​d​r​a​v​o​t​n​í​c​h​ ​s​t​u​d​i​í
		 */
		FZS: string
		/**
		 * R​e​k​t​o​r​á​t
		 */
		REK: string
		/**
		 * N​o​v​é​ ​t​e​c​h​n​o​l​o​g​i​e​ ​-​ ​v​ý​z​k​u​m​n​é​ ​c​e​n​t​r​u​m
		 */
		NTC: string
		/**
		 * U​n​i​v​e​r​z​i​t​a​ ​t​ř​e​t​í​h​o​ ​v​ě​k​u
		 */
		U3V: string
		/**
		 * U​́​s​t​a​v​ ​j​a​z​y​k​o​v​é​ ​p​ř​i​́​p​r​a​v​y
		 */
		UJP: string
	}
}

export type TranslationFunctions = {
	cookies: {
		/**
		 * Webová stránka využívá cookies
		 */
		title: () => LocalizedString
		/**
		 * Webová stránka využívá cookies, které jsou nezbytné pro jeho správné fungování. Používáním této webové stránky souhlasíte se zásadami používání souborů cookies.
		 */
		description: () => LocalizedString
		/**
		 * Souhlasím
		 */
		accept: () => LocalizedString
	}
	navbar: {
		/**
		 * Pravidla
		 */
		rules: () => LocalizedString
		/**
		 * Výsledky
		 */
		results: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		login: () => LocalizedString
		/**
		 * Registrovat
		 */
		register: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		logout: () => LocalizedString
		/**
		 * Administrace
		 */
		administration: () => LocalizedString
		/**
		 * Nahrát aktivitu
		 */
		submission: () => LocalizedString
		/**
		 * Profil
		 */
		profile: () => LocalizedString
		/**
		 * Nastavení
		 */
		settings: () => LocalizedString
	}
	homepage: {
		/**
		 * Měsíční Vytrvalec
		 */
		title: () => LocalizedString
		statistics: {
			/**
			 * Statistiky
			 */
			title: () => LocalizedString
			/**
			 * UČASTNÍKŮ
			 */
			users: () => LocalizedString
		}
		/**
		 * Akce měsíční vytrvalec vznikla během zimního semestru v roce 2020. Tuto pohybovou soutěž připravila a zorganizovala Katedra tělesné výchovy Fakulty strojní Západočeské univerzity v Plzni s úmyslem rozhýbat studenty během distanční výuky, která probíhala na ZČU během koronavirové pandemie.
		 */
		intro: () => LocalizedString
		/**
		 * Předchozí ročníky
		 */
		past_seasons: () => LocalizedString
		/**
		 * Ročník
		 */
		current_year: () => LocalizedString
		/**
		 * Charita
		 */
		charity: () => LocalizedString
		about: {
			/**
			 * O výzvě
			 */
			title: () => LocalizedString
			/**
			 * Účastníci bojují čtyři týdny za svoje týmy (fakulta, VŠ ústav / rektorátní pracoviště / U3V) v počtu naběhaných a naježděných kilometrů. Ty se v rámci týmů sčítají a v závěru týdne určují počet bodů, které daný tým získá a podle toho se umístí v celkovém pořadí.
			 */
			content: () => LocalizedString
		}
	}
	registration: {
		/**
		 * Registrace
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		/**
		 * Jméno
		 */
		first_name: () => LocalizedString
		/**
		 * Příjmení
		 */
		last_name: () => LocalizedString
		/**
		 * Fakulta
		 */
		faculty: () => LocalizedString
		/**
		 * Souhlasím se zpracováním osobních údajů
		 */
		gdpr: () => LocalizedString
		/**
		 * Registrovat
		 */
		submit: () => LocalizedString
		errors: {
			email: {
				/**
				 * E-mailová adresa nesmí být prázdná.
				 */
				blank: () => LocalizedString
				/**
				 * Tato e-mailová adresa byla již registrována.
				 */
				not_unique: () => LocalizedString
			}
			password: {
				/**
				 * Heslo nesmí být prázdné.
				 */
				blank: () => LocalizedString
				/**
				 * Vaše heslo musí obsahovat alespoň 8 znaků a alespoň jedno číslo a speciální znak.
				 */
				weak: () => LocalizedString
			}
			first_name: {
				/**
				 * Jméno nesmí být prázdné.
				 */
				blank: () => LocalizedString
			}
			last_name: {
				/**
				 * Příjmení nesmí být prázdné.
				 */
				blank: () => LocalizedString
			}
			faculty: {
				/**
				 * Vybraná fakulta není platná.
				 */
				invalid: () => LocalizedString
				/**
				 * Nepodarilo se najít fakulty
				 */
				no_faculties: () => LocalizedString
			}
			gdpr: {
				/**
				 * Prosím potvrďte souhlas se zpracováním osobních údajů.
				 */
				blank: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * Přihlášení
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		/**
		 * Přihlásení probehlo úspěšně
		 */
		success: () => LocalizedString
		/**
		 * Přihlášení selhalo
		 */
		error: () => LocalizedString
		errors: {
			email: {
				/**
				 * Vyplňte prosím svou e-mailovou adresu.
				 */
				blank: () => LocalizedString
			}
			password: {
				/**
				 * Vyplňte prosím své heslo.
				 */
				blank: () => LocalizedString
			}
			auth: {
				/**
				 * Neplatné přihlašovací údaje
				 */
				invalid_credentials: () => LocalizedString
			}
		}
		/**
		 * Přihlásit
		 */
		submit: () => LocalizedString
		forgotten: {
			/**
			 * Zapomenuté heslo
			 */
			title: () => LocalizedString
			/**
			 * Zapomněli jste heslo?
			 */
			prompt: () => LocalizedString
			/**
			 * Odeslat
			 */
			submit: () => LocalizedString
			/**
			 * Na e-mailovou adresu bude zaslán odkaz k obnovení hesla.
			 */
			description: () => LocalizedString
			/**
			 * E-mail odeslán
			 */
			success: () => LocalizedString
			/**
			 * Nastala chyba při odesílání e-mailu
			 */
			error: () => LocalizedString
		}
	}
	submission: {
		/**
		 * Aktivita
		 */
		title: () => LocalizedString
		/**
		 * Upravit aktivitu
		 */
		editingTitle: () => LocalizedString
		form: {
			/**
			 * Sem přetáhněte obrázek
			 */
			image: () => LocalizedString
			/**
			 * Vybrat obrázek
			 */
			chooseImage: () => LocalizedString
			/**
			 * Vzdálenost
			 */
			distance: () => LocalizedString
			/**
			 * Převýšení
			 */
			elevation: () => LocalizedString
			/**
			 * Aktivita
			 */
			activity: () => LocalizedString
			/**
			 * Nahrát
			 */
			submit: () => LocalizedString
			/**
			 * Upravit
			 */
			edit: () => LocalizedString
			/**
			 * Komentář k zamítnutí
			 */
			comment: () => LocalizedString
			/**
			 * Nahrání aktivity proběhlo úspěšně
			 */
			success: () => LocalizedString
			/**
			 * Při nahrávání aktivity došlo k chybě
			 */
			error: () => LocalizedString
			/**
			 * Smazat
			 */
			'delete': () => LocalizedString
			/**
			 * Opravdu chcete aktivitu smazat?
			 */
			deleteConfirm: () => LocalizedString
			/**
			 * Aktivita smazána
			 */
			deleteSuccessToast: () => LocalizedString
			/**
			 * Při mazání aktivity došlo k chybě
			 */
			deleteErrorToast: () => LocalizedString
			/**
			 * Aktivita upravena
			 */
			editSuccessToast: () => LocalizedString
			/**
			 * Při úpravě aktivity došlo k chybě
			 */
			editErrorToast: () => LocalizedString
			errors: {
				image: {
					/**
					 * Nahrajte prosím obrázek.
					 */
					blank: () => LocalizedString
					/**
					 * Nahrajte prosím platný obrázek.
					 */
					invalid: () => LocalizedString
					/**
					 * Obrázek je příliš veliký, maximální velikost obrázku je 4MB.
					 */
					too_large: () => LocalizedString
				}
				distance: {
					/**
					 * Zadejte prosím vzdálenost
					 */
					blank: () => LocalizedString
					/**
					 * Vzdálenost musí být kladné celé číslo
					 */
					invalid: () => LocalizedString
					/**
					 * Vzdálenost musí být kladné celé číslo
					 */
					negative: () => LocalizedString
				}
				elevation: {
					/**
					 * Převýšení musí být kladné celé číslo
					 */
					invalid: () => LocalizedString
					/**
					 * Převýšení musí být kladné celé číslo
					 */
					negative: () => LocalizedString
				}
				activity: {
					/**
					 * Prosím vyberte aktivitu.
					 */
					blank: () => LocalizedString
					/**
					 * Vybraná aktivita není platná.
					 */
					invalid: () => LocalizedString
				}
			}
		}
		state: {
			/**
			 * Zpracovává se
			 */
			pending: () => LocalizedString
			/**
			 * Schváleno
			 */
			accepted: () => LocalizedString
			/**
			 * Zamítnuto
			 */
			rejected: () => LocalizedString
		}
		errors: {
			/**
			 * Jiný administrátor změnil tuto aktivitu. Aktualizujte stránku a opakujte akci
			 */
			mismatch_updated_at: () => LocalizedString
		}
	}
	extraPoints: {
		/**
		 * Vzdálenost za 1 týden
		 */
		weekly_distance: () => LocalizedString
		/**
		 * Vzdálenost za 1 den
		 */
		daily_distance: () => LocalizedString
		/**
		 * Převýšení za týden
		 */
		weekly_elevation: () => LocalizedString
	}
	account: {
		/**
		 * Účet
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		/**
		 * Jméno
		 */
		first_name: () => LocalizedString
		/**
		 * Příjmení
		 */
		last_name: () => LocalizedString
		/**
		 * Fakulta
		 */
		faculty: () => LocalizedString
		/**
		 * Současné heslo
		 */
		old_password: () => LocalizedString
		/**
		 * Pokud některé údaje nesedí, kontaktujte prosím administrátora
		 */
		invalid_info: () => LocalizedString
		/**
		 * Uložit
		 */
		save: () => LocalizedString
		/**
		 * Údaje byly úspěšně změněny
		 */
		success: () => LocalizedString
		errors: {
			email: {
				/**
				 * E-mail nesmí být prázdný
				 */
				blank: () => LocalizedString
			}
			password: {
				/**
				 * Heslo nesmí být prázdné
				 */
				blank: () => LocalizedString
				/**
				 * Heslo je příliš slabé
				 */
				weak: () => LocalizedString
			}
			old_password: {
				/**
				 * Současne heslo nesmí být prázdné
				 */
				blank: () => LocalizedString
				/**
				 * Současne heslo není správné
				 */
				mismatch: () => LocalizedString
			}
		}
	}
	results: {
		/**
		 * Výsledky sezóny
		 */
		title: () => LocalizedString
		/**
		 * Výsledky
		 */
		results: () => LocalizedString
		week_picker: {
			/**
			 * Celá sezóna
			 */
			'0': () => LocalizedString
			/**
			 * První týden
			 */
			'1': () => LocalizedString
			/**
			 * Druhý týden
			 */
			'2': () => LocalizedString
			/**
			 * Třetí týden
			 */
			'3': () => LocalizedString
			/**
			 * Čtvrtý týden
			 */
			'4': () => LocalizedString
		}
		/**
		 * Zatím nejsou žádné výsledky pro tento týden či sezónu
		 */
		no_results: () => LocalizedString
		/**
		 * Fakulta
		 */
		faculty: () => LocalizedString
		/**
		 * Vzdálenost
		 */
		distance: () => LocalizedString
		/**
		 * Převýšení
		 */
		elevation: () => LocalizedString
		/**
		 * Body
		 */
		points: () => LocalizedString
	}
	profile: {
		/**
		 * Aktivity
		 */
		submissions: () => LocalizedString
		loading: {
			/**
			 * Načítání statistik...
			 */
			statistics: () => LocalizedString
			/**
			 * načítání aktivit...
			 */
			submissions: () => LocalizedString
		}
		/**
		 * Zatím nemáte žádné aktivity
		 */
		noSubmissions: () => LocalizedString
	}
	reset: {
		/**
		 * Změna hesla
		 */
		title: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		/**
		 * Heslo znova
		 */
		passwordRepeat: () => LocalizedString
		/**
		 * Heslo bylo změněno
		 */
		success: () => LocalizedString
		/**
		 * Nastala chyba při změně hesla
		 */
		error: () => LocalizedString
		/**
		 * Změnit
		 */
		submit: () => LocalizedString
	}
	activities: {
		/**
		 * Běh a chůze
		 */
		'Běh/Chůze': () => LocalizedString
		/**
		 * Kolo a koloběžka
		 */
		'Kolo/Koloběžka': () => LocalizedString
	}
	icons: {
		/**
		 * runner
		 */
		'Běh/Chůze': () => LocalizedString
		/**
		 * bike
		 */
		'Kolo/Koloběžka': () => LocalizedString
	}
	rules: {
		/**
		 * Pravidla
		 */
		title: () => LocalizedString
		/**
		 * Pravidla výzvy
		 */
		challengeTitle: () => LocalizedString
		intro: {
			/**
			 * Běhejte, choďte jezděte na kole, koloběžce, bruslích! Nejen, že uděláte něco pro svoje zdraví, ale přispějete na dobrou věc! Kilometry, které soutěžící urazí se přemění na koruny a přispějeme tím na charitu.
			 */
			content1: () => LocalizedString
			/**
			 * Průběžný počet najetých a uběhnutých kilometrů fakult a mimofakultních pracovišť budeme vyhodnocovat po týdnu a každá fakulta či pracoviště mají možnost získat body do celkového hodnocení.
			 */
			content2: () => LocalizedString
		}
		disciplines: {
			/**
			 * Soutěž probíhá ve dvou disciplínách
			 */
			title: () => LocalizedString
		}
		progress: {
			/**
			 * Průběh soutěže
			 */
			title: () => LocalizedString
			/**
			 * Uživatelé zaznamenávají své pohybové aktivity prostřednictvím některé mobilní aplikace na svůj telefon a nahrají je na tento portál.
			 */
			content1: () => LocalizedString
			/**
			 * Každý týden se vyhodnocuje počet uražených kilometrů v daných disciplínách. První tým dostane v každé disciplíně např. 15 bodů (podle počtu zůčastněných fakult a pracovišť), druhý 14 bodu, třetí 13 bodů, apod. Celkovým vítězem výzvy se stane tým, který získá nejvíce bodů za 4 týdny v součtu obou disciplín.
			 */
			content2: () => LocalizedString
		}
		extraPoints: {
			/**
			 * Extra body!
			 */
			title: () => LocalizedString
			/**
			 * Jednotlivci mohou pro svou fakultu získat extra body.
			 */
			intro: () => LocalizedString
			thirdWeek: {
				/**
				 * Třetí týden
				 */
				title: () => LocalizedString
				/**
				 * pro jednotlivce, který uběhne/ujde/ujede nejvíce kilometrů v jednom dni v dané disciplíně.
				 */
				extraOne: () => LocalizedString
				/**
				 * pro jednotlivce s největším součtem kilometrů za celý týden v dané disciplíně.
				 */
				extraTwo: () => LocalizedString
			}
			fourthWeek: {
				/**
				 * Čtvrtý týden
				 */
				title: () => LocalizedString
				/**
				 * pro jednotlivce s největším převýšením za celý týden v dané disciplíně. Chůze více než 1000m a jízda více než 1500m.
				 */
				extraOne: () => LocalizedString
			}
			/**
			 * Extra bod
			 */
			extraPoint: () => LocalizedString
			/**
			 * Extra body
			 */
			extraPoints: () => LocalizedString
		}
	}
	faculties: {
		/**
		 * Fakulta aplikovaných věd
		 */
		FAV: () => LocalizedString
		/**
		 * Fakulta designu a umění Ladislava Sutnara
		 */
		FDU: () => LocalizedString
		/**
		 * Fakulta ekonomická
		 */
		FEK: () => LocalizedString
		/**
		 * Fakulta elektrotechnická
		 */
		FEL: () => LocalizedString
		/**
		 * Fakulta filozofická
		 */
		FF: () => LocalizedString
		/**
		 * Fakulta pedagogická
		 */
		FPE: () => LocalizedString
		/**
		 * Fakulta právnická
		 */
		FPR: () => LocalizedString
		/**
		 * Fakulta strojní
		 */
		FST: () => LocalizedString
		/**
		 * Fakulta zdravotních studií
		 */
		FZS: () => LocalizedString
		/**
		 * Rektorát
		 */
		REK: () => LocalizedString
		/**
		 * Nové technologie - výzkumné centrum
		 */
		NTC: () => LocalizedString
		/**
		 * Univerzita třetího věku
		 */
		U3V: () => LocalizedString
		/**
		 * Ústav jazykové přípravy
		 */
		UJP: () => LocalizedString
	}
}

export type Formatters = {}
