// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'cs'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		/**
		 * P​r​a​v​i​d​l​a
		 */
		rules: string
		/**
		 * V​ý​s​l​e​d​k​y
		 */
		results: string
		/**
		 * P​ř​i​h​l​á​s​i​t​ ​s​e
		 */
		login: string
		/**
		 * R​e​g​i​s​t​r​o​v​a​t
		 */
		register: string
		/**
		 * O​d​h​l​á​s​i​t​ ​s​e
		 */
		logout: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​c​e
		 */
		administration: string
	}
	homepage: {
		/**
		 * M​ě​s​í​č​n​í​ ​V​y​t​r​v​a​l​e​c
		 */
		title: string
		statistics: {
			/**
			 * U​Č​A​S​T​N​Í​K​Ů
			 */
			users: string
		}
	}
	registration: {
		/**
		 * R​e​g​i​s​t​r​a​c​e
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		/**
		 * J​m​é​n​o
		 */
		first_name: string
		/**
		 * P​ř​í​j​m​e​n​í
		 */
		last_name: string
		/**
		 * F​a​k​u​l​t​a
		 */
		faculty: string
		/**
		 * S​o​u​h​l​a​s​í​m​ ​s​e​ ​z​p​r​a​c​o​v​á​n​í​m​ ​o​s​o​b​n​í​c​h​ ​ú​d​a​j​ů
		 */
		gdpr: string
		/**
		 * R​e​g​i​s​t​r​o​v​a​t
		 */
		submit: string
		errors: {
			email: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​o​u​ ​e​-​m​a​i​l​o​v​o​u​ ​a​d​r​e​s​u​.
				 */
				blank: string
				/**
				 * T​a​t​o​ ​e​-​m​a​i​l​o​v​a​́​ ​a​d​r​e​s​a​ ​b​y​l​a​ ​j​i​z​̌​ ​r​e​g​i​s​t​r​o​v​a​́​n​a​.
				 */
				not_unique: string
			}
			password: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​h​e​s​l​o​.
				 */
				blank: string
				/**
				 * V​a​š​e​ ​h​e​s​l​o​ ​m​u​s​í​ ​o​b​s​a​h​o​v​a​t​ ​a​l​e​s​p​o​ň​ ​8​ ​z​n​a​k​ů​ ​a​ ​a​l​e​s​p​o​ň​ ​j​e​d​n​o​ ​č​í​s​l​o​ ​a​ ​s​p​e​c​i​á​l​n​í​ ​z​n​a​k​.
				 */
				weak: string
			}
			first_name: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​j​m​é​n​o​.
				 */
				blank: string
			}
			last_name: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​p​ř​í​j​m​e​n​í​.
				 */
				blank: string
			}
			faculty: {
				/**
				 * V​y​b​r​a​n​á​ ​f​a​k​u​l​t​a​ ​n​e​n​i​́​ ​p​l​a​t​n​á​.
				 */
				invalid: string
			}
			gdpr: {
				/**
				 * P​r​o​s​í​m​ ​p​o​t​v​r​ď​t​e​ ​s​o​u​h​l​a​s​ ​s​e​ ​z​p​r​a​c​o​v​á​n​í​m​ ​o​s​o​b​n​í​c​h​ ​ú​d​a​j​ů​.
				 */
				blank: string
			}
		}
	}
	login: {
		/**
		 * P​ř​i​h​l​á​š​e​n​í
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		errors: {
			email: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​o​u​ ​e​-​m​a​i​l​o​v​o​u​ ​a​d​r​e​s​u​.
				 */
				blank: string
			}
			password: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​h​e​s​l​o​.
				 */
				blank: string
			}
		}
		/**
		 * P​ř​i​h​l​á​s​i​t
		 */
		submit: string
	}
}

export type TranslationFunctions = {
	navbar: {
		/**
		 * Pravidla
		 */
		rules: () => LocalizedString
		/**
		 * Výsledky
		 */
		results: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		login: () => LocalizedString
		/**
		 * Registrovat
		 */
		register: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		logout: () => LocalizedString
		/**
		 * Administrace
		 */
		administration: () => LocalizedString
	}
	homepage: {
		/**
		 * Měsíční Vytrvalec
		 */
		title: () => LocalizedString
		statistics: {
			/**
			 * UČASTNÍKŮ
			 */
			users: () => LocalizedString
		}
	}
	registration: {
		/**
		 * Registrace
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		/**
		 * Jméno
		 */
		first_name: () => LocalizedString
		/**
		 * Příjmení
		 */
		last_name: () => LocalizedString
		/**
		 * Fakulta
		 */
		faculty: () => LocalizedString
		/**
		 * Souhlasím se zpracováním osobních údajů
		 */
		gdpr: () => LocalizedString
		/**
		 * Registrovat
		 */
		submit: () => LocalizedString
		errors: {
			email: {
				/**
				 * Vyplňte prosím svou e-mailovou adresu.
				 */
				blank: () => LocalizedString
				/**
				 * Tato e-mailová adresa byla již registrována.
				 */
				not_unique: () => LocalizedString
			}
			password: {
				/**
				 * Vyplňte prosím své heslo.
				 */
				blank: () => LocalizedString
				/**
				 * Vaše heslo musí obsahovat alespoň 8 znaků a alespoň jedno číslo a speciální znak.
				 */
				weak: () => LocalizedString
			}
			first_name: {
				/**
				 * Vyplňte prosím své jméno.
				 */
				blank: () => LocalizedString
			}
			last_name: {
				/**
				 * Vyplňte prosím své příjmení.
				 */
				blank: () => LocalizedString
			}
			faculty: {
				/**
				 * Vybraná fakulta není platná.
				 */
				invalid: () => LocalizedString
			}
			gdpr: {
				/**
				 * Prosím potvrďte souhlas se zpracováním osobních údajů.
				 */
				blank: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * Přihlášení
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		errors: {
			email: {
				/**
				 * Vyplňte prosím svou e-mailovou adresu.
				 */
				blank: () => LocalizedString
			}
			password: {
				/**
				 * Vyplňte prosím své heslo.
				 */
				blank: () => LocalizedString
			}
		}
		/**
		 * Přihlásit
		 */
		submit: () => LocalizedString
	}
}

export type Formatters = {}
