// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'cs'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	cookies: {
		/**
		 * W​e​b​o​v​á​ ​s​t​r​á​n​k​a​ ​v​y​u​ž​í​v​á​ ​c​o​o​k​i​e​s
		 */
		title: string
		/**
		 * W​e​b​o​v​á​ ​s​t​r​á​n​k​a​ ​v​y​u​ž​í​v​á​ ​c​o​o​k​i​e​s​,​ ​k​t​e​r​é​ ​j​s​o​u​ ​n​e​z​b​y​t​n​é​ ​p​r​o​ ​j​e​h​o​ ​s​p​r​á​v​n​é​ ​f​u​n​g​o​v​á​n​í​.​ ​P​o​u​ž​í​v​á​n​í​m​ ​t​é​t​o​ ​w​e​b​o​v​é​ ​s​t​r​á​n​k​y​ ​s​o​u​h​l​a​s​í​t​e​ ​s​e​ ​z​á​s​a​d​a​m​i​ ​p​o​u​ž​í​v​á​n​í​ ​s​o​u​b​o​r​ů​ ​c​o​o​k​i​e​s​.
		 */
		description: string
		/**
		 * S​o​u​h​l​a​s​í​m
		 */
		accept: string
	}
	navbar: {
		/**
		 * P​r​a​v​i​d​l​a
		 */
		rules: string
		/**
		 * V​ý​s​l​e​d​k​y
		 */
		results: string
		/**
		 * P​ř​i​h​l​á​s​i​t​ ​s​e
		 */
		login: string
		/**
		 * R​e​g​i​s​t​r​o​v​a​t
		 */
		register: string
		/**
		 * O​d​h​l​á​s​i​t​ ​s​e
		 */
		logout: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​c​e
		 */
		administration: string
		/**
		 * N​a​h​r​á​t​ ​a​k​t​i​v​i​t​u
		 */
		submission: string
	}
	homepage: {
		/**
		 * M​ě​s​í​č​n​í​ ​V​y​t​r​v​a​l​e​c
		 */
		title: string
		statistics: {
			/**
			 * U​Č​A​S​T​N​Í​K​Ů
			 */
			users: string
		}
	}
	registration: {
		/**
		 * R​e​g​i​s​t​r​a​c​e
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		/**
		 * J​m​é​n​o
		 */
		first_name: string
		/**
		 * P​ř​í​j​m​e​n​í
		 */
		last_name: string
		/**
		 * F​a​k​u​l​t​a
		 */
		faculty: string
		/**
		 * S​o​u​h​l​a​s​í​m​ ​s​e​ ​z​p​r​a​c​o​v​á​n​í​m​ ​o​s​o​b​n​í​c​h​ ​ú​d​a​j​ů
		 */
		gdpr: string
		/**
		 * R​e​g​i​s​t​r​o​v​a​t
		 */
		submit: string
		errors: {
			email: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​o​u​ ​e​-​m​a​i​l​o​v​o​u​ ​a​d​r​e​s​u​.
				 */
				blank: string
				/**
				 * T​a​t​o​ ​e​-​m​a​i​l​o​v​a​́​ ​a​d​r​e​s​a​ ​b​y​l​a​ ​j​i​z​̌​ ​r​e​g​i​s​t​r​o​v​a​́​n​a​.
				 */
				not_unique: string
			}
			password: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​h​e​s​l​o​.
				 */
				blank: string
				/**
				 * V​a​š​e​ ​h​e​s​l​o​ ​m​u​s​í​ ​o​b​s​a​h​o​v​a​t​ ​a​l​e​s​p​o​ň​ ​8​ ​z​n​a​k​ů​ ​a​ ​a​l​e​s​p​o​ň​ ​j​e​d​n​o​ ​č​í​s​l​o​ ​a​ ​s​p​e​c​i​á​l​n​í​ ​z​n​a​k​.
				 */
				weak: string
			}
			first_name: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​j​m​é​n​o​.
				 */
				blank: string
			}
			last_name: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​p​ř​í​j​m​e​n​í​.
				 */
				blank: string
			}
			faculty: {
				/**
				 * V​y​b​r​a​n​á​ ​f​a​k​u​l​t​a​ ​n​e​n​i​́​ ​p​l​a​t​n​á​.
				 */
				invalid: string
			}
			gdpr: {
				/**
				 * P​r​o​s​í​m​ ​p​o​t​v​r​ď​t​e​ ​s​o​u​h​l​a​s​ ​s​e​ ​z​p​r​a​c​o​v​á​n​í​m​ ​o​s​o​b​n​í​c​h​ ​ú​d​a​j​ů​.
				 */
				blank: string
			}
		}
	}
	login: {
		/**
		 * P​ř​i​h​l​á​š​e​n​í
		 */
		title: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * H​e​s​l​o
		 */
		password: string
		errors: {
			email: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​o​u​ ​e​-​m​a​i​l​o​v​o​u​ ​a​d​r​e​s​u​.
				 */
				blank: string
			}
			password: {
				/**
				 * V​y​p​l​ň​t​e​ ​p​r​o​s​i​́​m​ ​s​v​e​́​ ​h​e​s​l​o​.
				 */
				blank: string
			}
		}
		/**
		 * P​ř​i​h​l​á​s​i​t
		 */
		submit: string
	}
	submission: {
		/**
		 * A​k​t​i​v​i​t​a
		 */
		title: string
		form: {
			/**
			 * S​e​m​ ​p​ř​e​t​á​h​n​ě​t​e​ ​o​b​r​á​z​e​k
			 */
			image: string
			/**
			 * V​z​d​á​l​e​n​o​s​t
			 */
			distance: string
			/**
			 * P​ř​e​v​ý​š​e​n​í
			 */
			elevation: string
			/**
			 * A​k​t​i​v​i​t​a
			 */
			activity: string
			/**
			 * N​a​h​r​á​t
			 */
			submit: string
			errors: {
				image: {
					/**
					 * N​a​h​r​a​j​t​e​ ​p​r​o​s​í​m​ ​o​b​r​á​z​e​k​.
					 */
					blank: string
					/**
					 * N​a​h​r​a​j​t​e​ ​p​r​o​s​í​m​ ​p​l​a​t​n​ý​ ​o​b​r​á​z​e​k​.
					 */
					invalid: string
					/**
					 * O​b​r​á​z​e​k​ ​j​e​ ​p​ř​í​l​i​š​ ​v​e​l​i​k​ý​,​ ​m​a​x​i​m​á​l​n​í​ ​v​e​l​i​k​o​s​t​ ​o​b​r​á​z​k​u​ ​j​e​ ​4​M​B​.
					 */
					too_large: string
				}
				distance: {
					/**
					 * Z​a​d​e​j​t​e​ ​p​r​o​s​í​m​ ​v​z​d​á​l​e​n​o​s​t
					 */
					blank: string
					/**
					 * V​z​d​á​l​e​n​o​s​t​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					invalid: string
					/**
					 * V​z​d​á​l​e​n​o​s​t​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					negative: string
				}
				elevation: {
					/**
					 * P​ř​e​v​ý​š​e​n​í​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					invalid: string
					/**
					 * P​ř​e​v​ý​š​e​n​í​ ​m​u​s​í​ ​b​ý​t​ ​k​l​a​d​n​é​ ​c​e​l​é​ ​č​í​s​l​o
					 */
					negative: string
				}
				activity: {
					/**
					 * P​r​o​s​í​m​ ​v​y​b​e​r​t​e​ ​a​k​t​i​v​i​t​u​.
					 */
					blank: string
					/**
					 * V​y​b​r​a​n​á​ ​a​k​t​i​v​i​t​a​ ​n​e​n​i​́​ ​p​l​a​t​n​á​.
					 */
					invalid: string
				}
			}
		}
	}
}

export type TranslationFunctions = {
	cookies: {
		/**
		 * Webová stránka využívá cookies
		 */
		title: () => LocalizedString
		/**
		 * Webová stránka využívá cookies, které jsou nezbytné pro jeho správné fungování. Používáním této webové stránky souhlasíte se zásadami používání souborů cookies.
		 */
		description: () => LocalizedString
		/**
		 * Souhlasím
		 */
		accept: () => LocalizedString
	}
	navbar: {
		/**
		 * Pravidla
		 */
		rules: () => LocalizedString
		/**
		 * Výsledky
		 */
		results: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		login: () => LocalizedString
		/**
		 * Registrovat
		 */
		register: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		logout: () => LocalizedString
		/**
		 * Administrace
		 */
		administration: () => LocalizedString
		/**
		 * Nahrát aktivitu
		 */
		submission: () => LocalizedString
	}
	homepage: {
		/**
		 * Měsíční Vytrvalec
		 */
		title: () => LocalizedString
		statistics: {
			/**
			 * UČASTNÍKŮ
			 */
			users: () => LocalizedString
		}
	}
	registration: {
		/**
		 * Registrace
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		/**
		 * Jméno
		 */
		first_name: () => LocalizedString
		/**
		 * Příjmení
		 */
		last_name: () => LocalizedString
		/**
		 * Fakulta
		 */
		faculty: () => LocalizedString
		/**
		 * Souhlasím se zpracováním osobních údajů
		 */
		gdpr: () => LocalizedString
		/**
		 * Registrovat
		 */
		submit: () => LocalizedString
		errors: {
			email: {
				/**
				 * Vyplňte prosím svou e-mailovou adresu.
				 */
				blank: () => LocalizedString
				/**
				 * Tato e-mailová adresa byla již registrována.
				 */
				not_unique: () => LocalizedString
			}
			password: {
				/**
				 * Vyplňte prosím své heslo.
				 */
				blank: () => LocalizedString
				/**
				 * Vaše heslo musí obsahovat alespoň 8 znaků a alespoň jedno číslo a speciální znak.
				 */
				weak: () => LocalizedString
			}
			first_name: {
				/**
				 * Vyplňte prosím své jméno.
				 */
				blank: () => LocalizedString
			}
			last_name: {
				/**
				 * Vyplňte prosím své příjmení.
				 */
				blank: () => LocalizedString
			}
			faculty: {
				/**
				 * Vybraná fakulta není platná.
				 */
				invalid: () => LocalizedString
			}
			gdpr: {
				/**
				 * Prosím potvrďte souhlas se zpracováním osobních údajů.
				 */
				blank: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * Přihlášení
		 */
		title: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Heslo
		 */
		password: () => LocalizedString
		errors: {
			email: {
				/**
				 * Vyplňte prosím svou e-mailovou adresu.
				 */
				blank: () => LocalizedString
			}
			password: {
				/**
				 * Vyplňte prosím své heslo.
				 */
				blank: () => LocalizedString
			}
		}
		/**
		 * Přihlásit
		 */
		submit: () => LocalizedString
	}
	submission: {
		/**
		 * Aktivita
		 */
		title: () => LocalizedString
		form: {
			/**
			 * Sem přetáhněte obrázek
			 */
			image: () => LocalizedString
			/**
			 * Vzdálenost
			 */
			distance: () => LocalizedString
			/**
			 * Převýšení
			 */
			elevation: () => LocalizedString
			/**
			 * Aktivita
			 */
			activity: () => LocalizedString
			/**
			 * Nahrát
			 */
			submit: () => LocalizedString
			errors: {
				image: {
					/**
					 * Nahrajte prosím obrázek.
					 */
					blank: () => LocalizedString
					/**
					 * Nahrajte prosím platný obrázek.
					 */
					invalid: () => LocalizedString
					/**
					 * Obrázek je příliš veliký, maximální velikost obrázku je 4MB.
					 */
					too_large: () => LocalizedString
				}
				distance: {
					/**
					 * Zadejte prosím vzdálenost
					 */
					blank: () => LocalizedString
					/**
					 * Vzdálenost musí být kladné celé číslo
					 */
					invalid: () => LocalizedString
					/**
					 * Vzdálenost musí být kladné celé číslo
					 */
					negative: () => LocalizedString
				}
				elevation: {
					/**
					 * Převýšení musí být kladné celé číslo
					 */
					invalid: () => LocalizedString
					/**
					 * Převýšení musí být kladné celé číslo
					 */
					negative: () => LocalizedString
				}
				activity: {
					/**
					 * Prosím vyberte aktivitu.
					 */
					blank: () => LocalizedString
					/**
					 * Vybraná aktivita není platná.
					 */
					invalid: () => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
