apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          # TODO: tady zmenit na url
          # image: vytrvalec-client
          imagePullPolicy: Always
          image: ipmil.civ.zcu.cz:4567/webs/vytrvalec-client/app
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  selector:
    component: client
  ports:
    - port: 3000
      targetPort: 3000
